Media stack service
Miszo97/FavouriteNews pull request #29
Opened 2022-04-06 08:07 UTC by Miszo97

Add class MediaStackService that encapsulates all http calls to a news provider.

2022-04-06 08:09 UTC, Miszo97 commented on backend/services/media_stack_service.py
> +
Is there a better way of creating url from parameters than this approach?

2022-04-06 14:39 UTC, tomkeee requested changes

2022-04-06 14:39 UTC, tomkeee commented on backend/tests/services/cassettes/test_get_articles_by_parameters.yaml
> +    uri: http://api.mediastack.com/v1/news?access_key=162b82c434e7ba8482f5b81b8d3d6334&countries=us&languages=en&categories=general&sources=cnn&limit=25
We have to find a solution to make our news_endpoint and api_key secure

2022-04-06 14:39 UTC, tomkeee commented on backend/tests/services/test_media_stack_service.py
> +    assert len(articles) == 5
Maybe we should add tests with missing/invalid data, and assert the response status

2022-04-07 08:38 UTC, Miszo97 commented on backend/Pipfile
> +pytest-vcr = "*"
You are right. Thanks!

2022-04-07 08:38 UTC, Miszo97 commented on backend/tests/services/test_media_stack_service.py
> +    assert len(articles) == 5
Good point!

2022-04-07 08:41 UTC, Miszo97 commented on backend/tests/services/test_media_stack_service.py
> +    assert len(articles) == 5
Wait. What status? We don't test endpoints here :D

2022-04-07 09:06 UTC, tomkeee approved these changes

2022-04-07 09:06 UTC, tomkeee commented on backend/tests/services/test_media_stack_service.py
> +    assert len(articles) == 5
Yeah, that's true, my bad 😅

2022-04-07 09:08 UTC, tomkeee commented
Well Done 💪  !

2022-04-07 10:39 UTC, merged